apiVersion: v1
kind: Secret
metadata:
  name: admin-user
  namespace: eventbus
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=

---

apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: admin
  namespace: eventbus
spec:
  tags:
    - administrator
  rabbitmqClusterReference:
    name: rabbitmq-cluster1
  importCredentialsSecret:
    name: admin-user

---

apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbit-admin-permission
  namespace: eventbus
spec:
  vhost: "/"
  user: "admin" # name of the RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq-cluster1

---

apiVersion: v1
kind: Secret
metadata:
  name: proxy-user-credentials
  namespace: eventbus
type: Opaque
data:
  username: aHR0cC1wcm94eQ==
  password: cGFzc3dk

---

apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: http-proxy
  namespace: eventbus
spec:
  rabbitmqClusterReference:
    name: rabbitmq-cluster1
  importCredentialsSecret:
    name: proxy-user-credentials

---

apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbit-proxy-permission
  namespace: eventbus
spec:
  vhost: "/"
  user: "http-proxy" # name of the RabbitMQ user
  permissions:
    write: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq-cluster1


