apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress
spec:
  profile: empty # Do not install CRDs or the control plane
  components:
    ingressGateways:
      - name: ingressgateway
        namespace: eventbus
        enabled: true
        label:
          # Set a unique label for the gateway. This is required to ensure Gateways
          # can select this workload
          istio: ingressgateway
  values:
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: eventbus-gateway
  namespace: eventbus
spec:
  selector:
    app: istio-ingressgateway
  servers:
    - port:
        number: 8080
        name: http
        protocol: HTTP
      hosts:
        - "*"

---

#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: rabbit-console-rule
#  namespace: eventbus
#spec:
#  hosts:
#    - "*"
#  gateways:
#    - eventbus/eventbus-gateway
#  http:
#    - match:
#      - uri:
#          prefix: /
#      rewrite:
#        uri: /
#      route:
#        - destination:
#            port:
#              number: 15672
#            host: rabbitmq-cluster1.eventbus.svc.cluster.local
#          weight: 100
#
#---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rabbit-proxy-rule
  namespace: eventbus
spec:
  hosts:
    - "*"
  gateways:
    - eventbus-gateway
  http:
    - match:
      - uri:
          prefix: "/proxy"
      rewrite:
        uri: "/"
      route:
        - destination:
            port:
              number: 8080
            host: rabbit-http-proxy
          weight: 100
    - route:
        - destination:
            port:
              number: 15672
            host: rabbitmq-cluster1
          weight: 100
